'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18408
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
Partial Friend NotInheritable Class bdConfig
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As bdConfig = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New bdConfig()),bdConfig)
    
    Public Shared ReadOnly Property [Default]() As bdConfig
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("sa")>  _
    Public Property usuario() As String
        Get
            Return CType(Me("usuario"),String)
        End Get
        Set
            Me("usuario") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("MATI-D")>  _
    Public Property equipo() As String
        Get
            Return CType(Me("equipo"),String)
        End Get
        Set
            Me("equipo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("06qiad")>  _
    Public Property contraseña() As String
        Get
            Return CType(Me("contraseña"),String)
        End Get
        Set
            Me("contraseña") = value
        End Set
    End Property
End Class
